image:
  file: .gitpod/Dockerfile
tasks:
  - name: Install dependencies and run tests
    init: ./mvnw verify
vscode:
  # Please also update .devcontainer/devcontainer.json extensions
  extensions:
  - vscjava.vscode-java-pack
	- vscjava.vscode-java-debug
	- vscjava.vscode-maven
	- vscjava.vscode-gradle
	- vscjava.vscode-java-dependency
	- vscjava.vscode-java-test
	- vscjava.vscode-spring-boot-dashboard
	- vscjava.vscode-spring-initializr
	- redhat.java
	- vmware.vscode-boot-dev-pack
	- vmware.vscode-spring-boot
	- ms-azuretools.vscode-docker
	- redhat.vscode-xml
	- redhat.vscode-yaml
	- editorconfig.editorconfig
	- gabrielbb.vscode-lombok